Code. 

Multiplex Detection of Viruses using Hadamard Matrices. 
G. S. Beddard & B. Yorke, School of Chemistry, University of Leeds, LS2 9JT, UK

https://www.medrxiv.org/content/10.1101/2024.10.21.24315883v1

Email. g.s.beddard@leeds.ac.uk, b.a.yorke@leeds.ac.uk

In [1]:
# import all python add-ons etc that will be needed later on
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import time
from itertools import combinations

## Start of Hadamard Matrix generation

In [2]:
#------------
def valid_seq_length(n):       # check Hadamard sequence length for Quadratic Residue method only
    #print('{:s}'.format( 'valid Hadamard sequence lengths \n       n = ') )
    maxi = 230
    Hseq = np.zeros(maxi,dtype=int)
    for i in range(maxi):                   # produce Hadamard sequence numbers
        for m in range(0,maxi):
            if isprime(i) and i == 4*m + 3:
                #print( '{:s} {:d}'.format('      ', i ) )
                Hseq[i]=i
            pass
    if n in Hseq[0:maxi]:
        #print('{:s} {:d}'.format('Hadamard sequence length ok. n = ', n) ,end='')
        is_ok=True
    else:
        #print('{:s} {:d}\n'.format('*****   ERROR in Hadamard S sequence length ', n))
        is_ok=False
    return is_ok
#------------
# check if integer n is a prime, range starts with 2 and only needs to go up the squareroot of n
def isprime(n):              
    for x in range(2, int(n**0.5)+1):
        if n % x == 0:
            return False
    return True
#------------
# quadratic residue method, this generates more S matrices than the other methods.
def quadratic_hadamard(n):    
    #print('hadamard quadratic residue method ')
    init_list = np.zeros(n,dtype=int)

    for i in range(n):                     # make list n/2+1 values = 1 rest zeros so in same ratio as hadamard
        if i <= n//2 : init_list[i] = 1    # check integer division
        pass
    alist = np.zeros(n,dtype=int)
    for i in range(0,(n-1)//2):            # integer division
        alist[(i+1)*(i+1) % n] = 1         # alist = hadamard Srow need only go to half range of n as indices are symmetric
    alist[0] = 1
    Srow = list(alist)
    
    S = np.zeros((n,n),dtype = int)
    for i in range(n):
        for j in range(n):
            S[i,j]= Srow[n-1-j]
        Srow = np.roll(Srow, 1)             # rotate by 1 element at a time
        pass
    
    return S                               # returns S matrix
#------------
#print('Hadamard S matrices by Quadratic residue method')
#for i in range(1,200):
#    if valid_seq_length(i):
#        S = quadratic_hadamard(i)
#        print(i)
#        if i  <= 32 :
#            print('\n'.join( [''.join(['{:2}'.format(item) for item in row] ) for row in S] ) )
#        else:
#            print(''.join(['{:2}'.format(item) for item in S[0]]))
#            xs=''.join( str(S[0][i]) for i in range(len(S[0])) )
#            print(hex(int(xs,2)))
#    pass 

In [3]:
for i in range(110):
    if valid_seq_length(i) ==True:
        print(i,',',end='')

0 ,3 ,7 ,11 ,19 ,23 ,31 ,43 ,47 ,59 ,67 ,71 ,79 ,83 ,103 ,107 ,

In [4]:
#-------------
# shift register method S matrix size  2^k-1 , k = 2, 3, 4  etc
def shift_hadamard(num):                
    print(' shift register method')
    num = int(num) + 1

    def S_lineA(n,m):
        SL     = np.zeros(n,dtype=int)
        #tempS =  np.zeros(n,dtype=int)
        SL[0] = 1                               # set x^n = 1
        for j in range(2**n-1):
            #tempS = SL
            tmp = (SL[m] + SL[0]) % 2           # mod 2
            SL = np.roll(SL,-1)                 # shift array elements
            SL[n-1] = tmp                       # last one as x^n
            Srow[j] = SL[0]
        pass

    def S_lineB(n,ma,mb,mc):
        SL    = np.zeros(n,dtype=int)
        #tempS = np.zeros(n,dtype=int)
        SL[0] = 1                               # set x^n = 1
        for j in range(2**n-1):
            #tempS = SL
            tmp1 = (SL[ma] + SL[0]) % 2         # mod 2
            tmp2 = (SL[mb] + tmp1 ) % 2
            tmp  = (SL[mc] + tmp2 ) % 2
            SL = np.roll(SL,-1)
            SL[n-1] = tmp                       # last one as x^n
            Srow[j] = SL[0]
        pass

    for k in range(num-1,num):                  # can generate v large matrices, 2^8-1, 2^9-1
        n = 2**k-1
        print('{:s} {:d} {:s} {:d} \n'.format('k = ', k, '; period, 2^k-1 = ' , n))
        Srow = np.zeros(n,dtype=int)            # holds one row of S matrix
        if k in [2,3,4,6,7,15]:	S_lineA(k,1)
        if k in [5,11]:	S_lineA(k,2)
        if k == 8:      S_lineB(k,1,5,6)
        if k == 9:      S_lineA(k,4)
        if k == 10:     S_lineA(k,3)
        if k == 12:     S_lineB(k,3,4,7)
        if k == 13:     S_lineB(k,1,3,4)
        if k == 14:     S_lineB(k,1,11,12)
        pass
        for i in range(n):
            print('{:1}'.format(Srow[n-1-i]),end='') 
            # n-1-i reverses Srow to get same order as quadratic residue method
            if (i+1) % 5 == 0 : print('  ',end='')
            pass
        print('\n')
        pass

        S = np.zeros((n,n),dtype = int)
        for i in range(n):
            for j in range(n):
                S[i,j] = Srow[n-1-j]
            Srow = np.roll(Srow, 1)                   # rotate by 1 element at a time
            pass

        #print( '{:s} {:4d}\n'.format(' S matrix with n = ', n) )
        #print('\n'.join( [''.join(['{:2}'.format(item) for item in row] ) for row in S] ) )
        #print('\n {:s}\n\n '.format( 'End of S matrix ') )

    return S
#------------
# 2^k+1  is size of matrix side
S = shift_hadamard(4)
print(S)

 shift register method
k =  4 ; period, 2^k-1 =  15 

11110  10110  01000  

[[1 1 1 1 0 1 0 1 1 0 0 1 0 0 0]
 [1 1 1 0 1 0 1 1 0 0 1 0 0 0 1]
 [1 1 0 1 0 1 1 0 0 1 0 0 0 1 1]
 [1 0 1 0 1 1 0 0 1 0 0 0 1 1 1]
 [0 1 0 1 1 0 0 1 0 0 0 1 1 1 1]
 [1 0 1 1 0 0 1 0 0 0 1 1 1 1 0]
 [0 1 1 0 0 1 0 0 0 1 1 1 1 0 1]
 [1 1 0 0 1 0 0 0 1 1 1 1 0 1 0]
 [1 0 0 1 0 0 0 1 1 1 1 0 1 0 1]
 [0 0 1 0 0 0 1 1 1 1 0 1 0 1 1]
 [0 1 0 0 0 1 1 1 1 0 1 0 1 1 0]
 [1 0 0 0 1 1 1 1 0 1 0 1 1 0 0]
 [0 0 0 1 1 1 1 0 1 0 1 1 0 0 1]
 [0 0 1 1 1 1 0 1 0 1 1 0 0 1 0]
 [0 1 1 1 1 0 1 0 1 1 0 0 1 0 0]]


In [5]:
#--------------
# S matrix size (2^k) -1 , k = 2, 3, 4 etc, replace each element by previous matrix
def doubling_hadamard(max_size):    
    
    print('Matrix doubling method size (2^k)-1, k=2,3.. :  k=',max_size , 'S matrix is not circulant')
    max_size = int(max_size)
    h0 = np.ones( (2,2),dtype = int )     # define initial Hadamard matrix
    h0[1,0] = -1
    #h0[1,1]=-1    # this way round leading row & col are 1's 
    print('initial form\n',h0,h0 @ h0.T)
    n = 2  # must be 2
    Htemp = h0
    for i in range(1,max_size):
        print(' {:s} {:d}'.format(' calculation continues, S size = ',2*2**i-1))
        Hnn = np.zeros((2*n,2*n),dtype=int)
        h0, h1 = Htemp.shape
        Hnn[0  : 0  + h0   , 0  : 0  + h1] =  Htemp
        Hnn[n  : n  + h0   , 0  : 0  + h1] = -Htemp 
        Hnn[0  : 0  + h0   , n  : n  + h1] =  Htemp
        Hnn[n  : n  + h0   , n  : n  + h1] =  Htemp
        print('Hnn\n',Hnn)
        n = 2*n
        s = Hnn.shape
        Htemp = np.zeros( s ,dtype = int)
        Htemp = Hnn[ 0:s[0],  0:s[0] ]

        sm = s[0] - 1
        Tmpmat = np.zeros((sm,sm),dtype=int)
        Smat   = np.zeros((sm,sm),dtype=int)
        Tmpmat= Htemp[1:sm+1, 0:sm]
        for ii in range(sm):
            for j in range(sm):
                if Tmpmat[ii,j] == 1:
                    Smat[ii,j]= 0
                else:
                    Smat[ii,j]= 1
                pass
    print('-------------------------------')
    return Smat
#-------------

smat = doubling_hadamard(4)  # 4 means  15 x 15 matrix
print('final S matrix \n',smat.shape)
print('\n'.join( [''.join(['{:2}'.format(item) for item in row] ) for row in smat] ) )

Matrix doubling method size (2^k)-1, k=2,3.. :  k= 4 S matrix is not circulant
initial form
 [[ 1  1]
 [-1  1]] [[2 0]
 [0 2]]
  calculation continues, S size =  3
Hnn
 [[ 1  1  1  1]
 [-1  1 -1  1]
 [-1 -1  1  1]
 [ 1 -1 -1  1]]
  calculation continues, S size =  7
Hnn
 [[ 1  1  1  1  1  1  1  1]
 [-1  1 -1  1 -1  1 -1  1]
 [-1 -1  1  1 -1 -1  1  1]
 [ 1 -1 -1  1  1 -1 -1  1]
 [-1 -1 -1 -1  1  1  1  1]
 [ 1 -1  1 -1 -1  1 -1  1]
 [ 1  1 -1 -1 -1 -1  1  1]
 [-1  1  1 -1  1 -1 -1  1]]
  calculation continues, S size =  15
Hnn
 [[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [-1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1]
 [-1 -1  1  1 -1 -1  1  1 -1 -1  1  1 -1 -1  1  1]
 [ 1 -1 -1  1  1 -1 -1  1  1 -1 -1  1  1 -1 -1  1]
 [-1 -1 -1 -1  1  1  1  1 -1 -1 -1 -1  1  1  1  1]
 [ 1 -1  1 -1 -1  1 -1  1  1 -1  1 -1 -1  1 -1  1]
 [ 1  1 -1 -1 -1 -1  1  1  1  1 -1 -1 -1 -1  1  1]
 [-1  1  1 -1  1 -1 -1  1 -1  1  1 -1  1 -1 -1  1]
 [-1 -1 -1 -1 -1 -1 -1 -1  1  1  1  1  1  1  1  1]
 [ 1 -1  

In [6]:
#This Python code was originally based on the R code of J. Steepleton, "Constructions of Hadamard Matrices" (2019). 
#Chancellor’s Honors Program Projects. https://trace.tennessee.edu/utk_chanhonoproj/2266

# matrix size;  m = 28  so divisible by 4 
# 2^k(p+1) = 28 when k=2, p=13

#-------------------------------
def legendre(p):                      # Legendre symbols, see Wikipedia
    leg = np.zeros(p,dtype=int)
    for i in range(p):
        temp = i**((p-1)/2) % p
        if temp > 1:
            temp = -1
        leg[i] = temp
    
    return leg[1:]                    # reverse order 
#--------------------------------

def Hadamard28(L,p):                       # form Hadamard 28 by 28 matrix   
    
    Had28 = np.zeros((2*(p+1),2*(p+1)),dtype=int)
    B     = np.zeros((p+1,p+1),dtype=int)      # insert Q into B as 2nd row & second column
    Q     = np.zeros((p,p),dtype=int)
    Q[0,1:] = L[:]                         # Legendre
    for i in range(1,p):                   # roll vector all except first 
        Q[i,:] = np.roll(Q[0,:],i)
    Q[0,0] = 0    
    # from now on is book-keeping, 
    # insert Q into B as 2nd row & second column  
    for i in range(p+1):
        B[0,i] = 1
        B[i,0] = 1
    
    for i in range(1,p+1):
        for j in range(1,p+1):
            B[i,j] = Q[i-1, j-1]
    B[0,0] = 0
    
    for i in range(0,p+1):                  # S matrix so fill matrix with 1& 0 instead of 1, -1
        for j in range(0,p+1):
            if B[i,j] == 1: 
                Had28[i+i-1  ,j+j-1] = 1
                Had28[i+i-1  ,j+j]   = 1
                Had28[i+i    ,j+j-1] = 1
                Had28[i+i    ,j+j]   = 0
                
            if B[i,j] == -1: 
                Had28[i+(i-1),j+(j-1)] = 0
                Had28[i+(i-1),j+j]     = 0
                Had28[i+i    ,j+(j-1)] = 0
                Had28[i+i    ,j+j]     = 1
                
            if B[i,j] == 0: 
                Had28[i+(i-1),j+(j-1)] = 1
                Had28[i+(i-1),j+j]     = 0
                Had28[i+i    ,j+(j-1)] = 0
                Had28[i+i    ,j+j]     = 0   
    
    return Had28 
#----------------------------------------

if __name__== '__main__':

    p = 13                                        # size = 2^k(p+1), in this case k=1
    L     = legendre(p)
    Had28 = Hadamard28(L,p)

    S28 = Had28[:-1,:-1]                          # make S matrix

    print('print S = 27 matrix,\nsize = ',len(S28[0,:]),len(S28[:,0])  ) 
    
for i in range(0,2*(p+1)-1):
    print('{:4d}'.format(i),end='  |  ')
    for j in range(0,2*(p+1)-1):
        temp = S28[j,i]
        print(temp,end=' ')
    print()


print S = 27 matrix,
size =  27 27
   0  |  0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 
   1  |  1 1 0 1 1 0 0 1 1 1 1 0 0 0 0 0 0 0 0 1 1 1 1 0 0 1 1 
   2  |  0 0 0 1 0 0 1 1 0 1 0 0 1 0 1 0 1 0 1 1 0 1 0 0 1 1 0 
   3  |  1 1 1 1 0 1 1 0 0 1 1 1 1 0 0 0 0 0 0 0 0 1 1 1 1 0 0 
   4  |  0 1 0 0 0 1 0 0 1 1 0 1 0 0 1 0 1 0 1 0 1 1 0 1 0 0 1 
   5  |  1 0 0 1 1 1 0 1 1 0 0 1 1 1 1 0 0 0 0 0 0 0 0 1 1 1 1 
   6  |  0 0 1 1 0 0 0 1 0 0 1 1 0 1 0 0 1 0 1 0 1 0 1 1 0 1 0 
   7  |  1 1 1 0 0 1 1 1 0 1 1 0 0 1 1 1 1 0 0 0 0 0 0 0 0 1 1 
   8  |  0 1 0 0 1 1 0 0 0 1 0 0 1 1 0 1 0 0 1 0 1 0 1 0 1 1 0 
   9  |  1 1 1 1 1 0 0 1 1 1 0 1 1 0 0 1 1 1 1 0 0 0 0 0 0 0 0 
  10  |  0 1 0 1 0 0 1 1 0 0 0 1 0 0 1 1 0 1 0 0 1 0 1 0 1 0 1 
  11  |  1 0 0 1 1 1 1 0 0 1 1 1 0 1 1 0 0 1 1 1 1 0 0 0 0 0 0 
  12  |  0 0 1 1 0 1 0 0 1 1 0 0 0 1 0 0 1 1 0 1 0 0 1 0 1 0 1 
  13  |  1 0 0 0 0 1 1 1 1 0 0 1 1 1 0 1 1 0 0 1 1 1 1 0 0 0 0 
  14  |  0 0 1 0 1 1 0 1 0 0 1 1 0 0 0 1 0 0 1 1 0 1 0 0 1 0 1 
  15 

## End of Hadamard matrix generation
## Calculation to find doubles

In [7]:
# This code calculated the list of row to use as described in case(iii) of table 1.
# No checking is made on input numbers, i.e. rows or size of matrix. 
# These numbers can be found in table 1.

#--------------------------------------
def allcombs(alist, num):
    return list(combinations(alist,num))
#---------------------------------------
def doubles(r,m):                                  # doubles as in case(iii) table 1
    
    t = time.process_time()
    colx = m - 1
    sylv = False
    
    if m == 7 and sylv == True:
            S = doubling_hadamard(3)                # is same as quadratic residue matrix
    
    if m == 15 :
        if sylv == False:
            S = shift_hadamard(4)
        else:
            S = doubling_hadamard(4)
    if m == 27:                                     # make Had 28 matrix then S matrix
        p = 13
        L = legendre(p)                             # Legendre bracket
        Had28 = Hadamard28(L,p)
        S = Had28[:-1,:-1] 
        
    if m in [7, 11, 19, 23, 31]:
        S = quadratic_hadamard(m)
    
    print('\n',S,'\n')
    
    n = m                                            # n = columns, m = rows
    
    S[:,colx] = 10                                   # removed column given impossible value
    
    allones = np.zeros(r,dtype=int)
    for i in range(r):
        allones[i] = 1
    
    print('new S matrix')
    for i in range(n):
        print(chr(i+65), S[i,:] )
    
    alist = [ str(chr(i+65)) for i in range(n) ]      # letter for each row A,B,C...
    
    comblist = allcombs(alist, r)                     # combinations r at a time 
    
    print('number of combinations', len(comblist),'\n' )
    
    blist   = [i for i in range(n)]                   # combinations 2 at at time to check doubles
    twocomb = allcombs(blist,2)
    lentc   = len(twocomb)
    
    acol    = np.zeros((r,n),dtype=int)               # r is row, n is column
    num_dups= 0
    znum    = 0
    for k in range(len(comblist)):                    # k is index of combination list
        
        temp = comblist[k]                            # list of rows A, B etc
        for i in range(n):                            # n is length of any row
            for j in range(r):                        # r is number or rows used in comblist
                acol[j,i] = S[ord(temp[j])-65,i ]     # get integer from A,B, C etc the get S column element
              
        # now check for doubles
        dups = False
        for i in range(n):
            for j in range(i):
                if i != j:
                    if np.array_equal(acol[:,i], acol[:,j]):
                        num_dups = num_dups + 1
                        dups = True
                        pass
                pass
            pass
        if dups == False:
            Q = 0
            # now check for sums use twocomb as list of pairs
            s = 0
            for i in range(n):
                for j in range(lentc):
                    k0 = twocomb[j][0]
                    k1 = twocomb[j][1]
                    temp = np.add( acol[: ,k0 ],  acol[: ,k1 ])
                    for m in range(r):
                        if temp[m] == 2:
                            temp[m] = 1
                    if np.array_equal(temp, acol[:,i]) or np.array_equal(temp,allones): # *** test all ones ***
                        Q = 1
                        s = s + 1
                        # is not suitable so no need to carry on 
            #if Q == 1:
            #    print('  sum fails',comblist[k],s)
            #else:
            if Q == 0:
                znum = znum + 1
                print(k,'**** IS OK',comblist[k], s  )
                for i in range(len(comblist[k] )):
                    ii = ord(comblist[k][i]) - 65
    
        if k % 1000 == 0:
            print('number tested =',k, ' .. continues')
        pass
    delta_time = int(time.process_time() - t )
    print(znum, ' found')   
    print('finished',len(comblist)-num_dups, 'time =', delta_time,' secs')
    pass
#-----------------------------------------------------

if __name__=='__main__':
    
    r = 6                               # rows
    m = 11                              # S matrix size
    doubles(r,m)
#-----------------


 [[0 1 0 0 0 1 1 1 0 1 1]
 [1 0 0 0 1 1 1 0 1 1 0]
 [0 0 0 1 1 1 0 1 1 0 1]
 [0 0 1 1 1 0 1 1 0 1 0]
 [0 1 1 1 0 1 1 0 1 0 0]
 [1 1 1 0 1 1 0 1 0 0 0]
 [1 1 0 1 1 0 1 0 0 0 1]
 [1 0 1 1 0 1 0 0 0 1 1]
 [0 1 1 0 1 0 0 0 1 1 1]
 [1 1 0 1 0 0 0 1 1 1 0]
 [1 0 1 0 0 0 1 1 1 0 1]] 

new S matrix
A [ 0  1  0  0  0  1  1  1  0  1 10]
B [ 1  0  0  0  1  1  1  0  1  1 10]
C [ 0  0  0  1  1  1  0  1  1  0 10]
D [ 0  0  1  1  1  0  1  1  0  1 10]
E [ 0  1  1  1  0  1  1  0  1  0 10]
F [ 1  1  1  0  1  1  0  1  0  0 10]
G [ 1  1  0  1  1  0  1  0  0  0 10]
H [ 1  0  1  1  0  1  0  0  0  1 10]
I [ 0  1  1  0  1  0  0  0  1  1 10]
J [ 1  1  0  1  0  0  0  1  1  1 10]
K [ 1  0  1  0  0  0  1  1  1  0 10]
number of combinations 462 

number tested = 0  .. continues
192 **** IS OK ('A', 'C', 'G', 'H', 'I', 'K') 0
1  found
finished 462 time = 3  secs
